/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mon_aigle;

import com.microsoft.sqlserver.jdbc.SQLServerException;
import java.sql.*;
import java.text.*;
import java.util.Date;
import java.util.logging.*;
import javax.swing.*;

/**
 *
 * @author Hoang Phuc
 */
public class QuanLyMuonSach extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyMuonTraSach
     */
    String sqlServer = "localhost";
    String port = "1433";
    String user = "sa1";
    String passWord = "123";
    String database = "QuanLyThuVien";
    String url = "jdbc:sqlserver://" + sqlServer + ":" + port + ";user=" + user + ";password=" + passWord + ";databaseName=" + database + ";encrypt=false";

    public QuanLyMuonSach() {
        setTitle("Quản lý mượn sách");
        setLocation(400, 100);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnMuonSach = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        txtIDSach = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtNgayMuon = new javax.swing.JTextField();
        txtNgayTra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIDSV = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("ID sách");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Tên sách");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Họ tên sinh viên");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Ngày mượn");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Ngày trả");

        btnMuonSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMuonSach.setText("Mượn sách");
        btnMuonSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuonSachActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        txtIDSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIDSach.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIDSachFocusLost(evt);
            }
        });
        txtIDSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtIDSachMouseExited(evt);
            }
        });

        txtTen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTen.setEnabled(false);

        txtHoTen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtHoTen.setEnabled(false);

        txtNgayMuon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNgayMuon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNgayMuonFocusLost(evt);
            }
        });

        txtNgayTra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("ID sinh viên");

        txtIDSV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIDSV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIDSVFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btnMuonSach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThoat)
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIDSach, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIDSV, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(62, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtIDSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtIDSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMuonSach)
                    .addComponent(btnThoat))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void hienThiTenSach(String ID) throws SQLException {
        // 2. Open connection
        try (Connection con = DriverManager.getConnection(url)) {
            // 3. Create Statement
            Statement st = con.createStatement();
            // 4. Execute query
            String sqlInsert = "SELECT TenSach FROM QuanLySach WHERE IDsach='" + ID + "';";
            ResultSet rs = st.executeQuery(sqlInsert);
            while (rs.next()) {
                String tenSach = rs.getString("TenSach");
                txtTen.setText(tenSach);
                // print the results
            }
            rs.close();
            st.close();
            // 5. Close connection
            con.close();
        } catch (SQLServerException e) {
            System.out.println(e);
        }
    }

    void hienThiTenSinhVien(String ID) throws SQLException {
        // 2. Open connection
        try (Connection con = DriverManager.getConnection(url)) {
            // 3. Create Statement
            Statement st = con.createStatement();
            // 4. Execute query
            String sqlInsert = "SELECT TenSinhVien FROM QuanLySinhVien WHERE IDsinhvien='" + ID + "';";
            ResultSet rs = st.executeQuery(sqlInsert);
            while (rs.next()) {
                String tenSinhVien = rs.getString("TenSinhVien");
                txtHoTen.setText(tenSinhVien);
                // print the results
            }
            rs.close();
            st.close();
            // 5. Close connection
            con.close();
        } catch (SQLServerException e) {
            System.out.println(e);
        }
    }

    void themDuLieu() throws SQLException {
        // 2. Open connection
        try (Connection con = DriverManager.getConnection(url)) {
            String ngayMuon = txtNgayMuon.getText();
            String ngayTra = txtNgayTra.getText();
            String idSinhVien = txtIDSV.getText();
            String idSach = txtIDSach.getText();
            // 3. Create Statement
            Statement st = con.createStatement();
            // 4. Execute query
            String sqlInsert = "INSERT INTO QuanLyMuonTra(IDsach, IDsinhvien, NgayMuon, NgayTra) VALUES ('" + idSach + "', '" + idSinhVien + "', '" + ngayMuon + "', '" + ngayTra + "')";
            ResultSet rs = st.executeQuery(sqlInsert);
            rs.close();
            st.close();
            // 5. Close connection
            con.close();
        } catch (SQLServerException e) {
            System.out.println(e);
        }
    }

    void batLoiDate() throws ParseException, SQLException {
        try {
            String muon = txtNgayMuon.getText();
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date ngayMuon = dateFormat.parse(muon);
            txtNgayMuon.setText(String.valueOf(new SimpleDateFormat("yyyy-MM-dd").format(ngayMuon)));
            String tra = txtNgayTra.getText();
            Date ngayTra = dateFormat.parse(tra);
            if (ngayMuon.before(ngayTra)) {
                txtNgayTra.setText(String.valueOf(new SimpleDateFormat("yyyy-MM-dd").format(ngayTra)));
                themDuLieu();
            } else {
                JOptionPane.showMessageDialog(this, "Ngày trả phải sau ngày mượn");
            }
        } catch (ParseException parseException) {
            JOptionPane.showMessageDialog(this, "Sai định dạng");
        }
    }

    private void btnMuonSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuonSachActionPerformed
        try {
            batLoiDate();
        } catch (ParseException | SQLException ex) {
            Logger.getLogger(QuanLyMuonSach.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMuonSachActionPerformed

    private void txtIDSachFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDSachFocusLost
        try {
            hienThiTenSach(txtIDSach.getText());
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyMuonSach.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtIDSachFocusLost

    private void txtIDSachMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIDSachMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDSachMouseExited

    private void txtIDSVFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDSVFocusLost
        try {
            hienThiTenSinhVien(txtIDSV.getText());
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyMuonSach.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtIDSVFocusLost

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void txtNgayMuonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNgayMuonFocusLost

    }//GEN-LAST:event_txtNgayMuonFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyMuonSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyMuonSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyMuonSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyMuonSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyMuonSach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMuonSach;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtIDSV;
    private javax.swing.JTextField txtIDSach;
    private javax.swing.JTextField txtNgayMuon;
    private javax.swing.JTextField txtNgayTra;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
