package mon_aigle;

import com.microsoft.sqlserver.jdbc.SQLServerException;
import java.sql.*;
import java.util.*;
import java.util.logging.*;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 *
 */
public class ThongKeSach extends javax.swing.JFrame {

    /**
     * Creates new form ThongKeSach
     */
    boolean fill = false;
    Connection con = null;
    PreparedStatement pstDetails = null;
    ResultSet rs;
    private DefaultTableModel tbl;
    private DefaultTableModel tbl2;
    private DefaultTableModel tbl3;
    Vector data = new Vector();
    Vector col = new Vector();
    Vector data2 = new Vector();
    Vector col2 = new Vector();
    Vector data3 = new Vector();
    Vector col3 = new Vector();

    public ThongKeSach() {
        setLocation(300, 100);
        initComponents();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String sqlServer = "localhost";
            String port = "1433";
            String user = "sa1";
            String passWord = "123";
            String database = "QuanLyThuVien";
            String url = "jdbc:sqlserver://" + sqlServer + ":" + port + ";user=" + user + ";password=" + passWord + ";databaseName=" + database + ";encrypt=false";
            con = DriverManager.getConnection(url);
            this.loadData1(txtTim.getText());
            this.loadData2(txtTim.getText());
            this.loadData3();
            fill = true;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private void loadData1(String input) throws SQLException {
        try {
            Statement st = con.createStatement();
            rs = st.executeQuery("select IDsach 'Mã sách', count(IDsach) 'Số lượng' from QuanLyMuonTra where month(NgayMuon) = " + input + " group by IDsach");
            data.removeAllElements();
            if (!fill) {
//get header
                ResultSetMetaData rsmd = rs.getMetaData();
                int n = rsmd.getColumnCount();
                col.add(rsmd.getColumnName(1));
                col.add(rsmd.getColumnName(2));
            }
//get data
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                data.add(v);
            }
            tbl = new DefaultTableModel(data, col);
            this.tblSachMuon.setModel(tbl);
            rs.close();
            st.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private void loadData2(String input) throws SQLException {
        try {
            Statement st = con.createStatement();
            rs = st.executeQuery("select IDsach 'Mã sách', count(IDsach) 'Số lượng' from QuanLyMuonTra where month(NgayTra) = " + input + " group by IDsach");
            data2.removeAllElements();
            if (!fill) {
//get header
                ResultSetMetaData rsmd = rs.getMetaData();
                int n = rsmd.getColumnCount();
                col2.add(rsmd.getColumnName(1));
                col2.add(rsmd.getColumnName(2));
            }
//get data
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                data2.add(v);
            }
            tbl2 = new DefaultTableModel(data2, col2);
            this.tblSachTra.setModel(tbl2);
            rs.close();
            st.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private void loadData3() throws SQLException {
        try {
            Statement st = con.createStatement();
            rs = st.executeQuery("select IDsach 'Mã sách', count(IDsach) 'Số lượng' from QuanLyMuonTra where NgayTra is null group by IDsach");
            data3.removeAllElements();
            if (!fill) {
//get header
                ResultSetMetaData rsmd = rs.getMetaData();
                int n = rsmd.getColumnCount();
                col3.add(rsmd.getColumnName(1));
                col3.add(rsmd.getColumnName(2));
            }
//get data
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                data3.add(v);
            }
            tbl3 = new DefaultTableModel(data3, col3);
            this.tblSachTre.setModel(tbl3);
            rs.close();
            st.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTim = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTongSach = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSachMuon = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSachTra = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSachTre = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thống kê");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tháng:");

        txtTim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTim.setText("1");
        txtTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimActionPerformed(evt);
            }
        });

        btnTim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mon_aigle/New folder/search.png"))); // NOI18N
        btnTim.setText("Tìm ");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Thống kê sách mượn");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Thống kê sách trả");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Sách trễ hạn");

        lblTongSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTongSach.setText("Tổng sách: ");

        tblSachMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblSachMuon);

        tblSachTra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblSachTra);

        tblSachTre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblSachTre);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnTim)
                        .addGap(115, 115, 115)
                        .addComponent(lblTongSach, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim)
                    .addComponent(lblTongSach))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void tongSoSach() throws SQLException {
        String sqlServer = "localhost";
        String port = "1433";
        String user = "sa";
        String passWord = "sa";
        String database = "QuanLyThuVien";
        String url = "jdbc:sqlserver://" + sqlServer + ":" + port + ";user=" + user + ";password=" + passWord + ";databaseName=" + database + ";encrypt=false";
        // 2. Open connection
        try (Connection con = DriverManager.getConnection(url)) {
            // 3. Create Statement
            Statement st = con.createStatement();
            String sqlInsert = "SELECT COUNT(IDsach) 'TongSo' FROM QuanLySach;";
            ResultSet rs = st.executeQuery(sqlInsert);
            while (rs.next()) {
                String x = rs.getString("TongSo");
                lblTongSach.setText("Tổng sách: " + x);
            }
            rs.close();
            st.close();
            // 5. Close connection
            con.close();
        } catch (SQLServerException e) {
            System.out.println(e);
        }
    }

    private void txtTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            tongSoSach();
        } catch (SQLException ex) {
            Logger.getLogger(ThongKeSach.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        try {
            int search = Integer.parseInt(txtTim.getText());
            if (search < 1 || search > 12) {
                JOptionPane.showMessageDialog(this, "Từ tháng 1 đến 12");
            } else {
                try {
                    tbl = new DefaultTableModel();
                    tbl2 = new DefaultTableModel();
                    tbl3 = new DefaultTableModel();
                    this.loadData1(txtTim.getText());
                    this.loadData2(txtTim.getText());
                    this.loadData3();
                } catch (SQLException ex) {
                    Logger.getLogger(ThongKeSach.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Tháng phải là số");
        }
    }//GEN-LAST:event_btnTimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKeSach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTongSach;
    private javax.swing.JTable tblSachMuon;
    private javax.swing.JTable tblSachTra;
    private javax.swing.JTable tblSachTre;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
